name: mocktest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  chewie: ^1.8.1
  equatable: ^2.0.3
  encrypt: ^5.0.1
  syncfusion_flutter_pdfviewer: ^25.1.41
  http: ^1.2.1
  just_audio: ^0.9.37
  audio_video_progress_bar: ^2.0.2
  syncfusion_flutter_core: ^25.2.3


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/font/

fonts:
    - family: inter
      fonts:
        - asset: font/Inter-Regular.tff
          style: regular